coverage:
  status:
    project:
      default:
        target: 30%
        threshold: 5%
    patch:
      default:
        target: 30%

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/

comment:
  layout: "reach, diff, flags, files"
  behavior: default
